### ISSUE TITLE
Run switch/case scripts

### ISSUE THREAD

**Issue by alexanderaucobo** [rolfwessels/Command.Bot#16]
Is there a possibillity to run switch/case statement like "test --test"
I use it on Linux :-)

**Comment by rolfwessels** [comment]
Hi, Thanks for the feedback. 

I'm not 100% what it is that you would like. Can you please try to describe it with a bit more detail?

I assume you have a bash script called test and you want to pass params to the script? Is that it ?

**Comment by alexanderaucobo** [comment]
Yes, exactly, that is it :-).  I mean i can declare that in the script and run the scripts with some parameters. And this parameter should be possible over slack. That where great when this are possible 👍 :-)

**Comment by rolfwessels** [comment]
Sorry for the delay.

I've been thinking about it. Was at first worried that you could somehow then get access to different parts of the server. However if i made it that you could only every add `--XXX` then i think it should be okay. I will have a look at it when I have some time.

**Comment by rolfwessels** [comment]
Sorry for the delay I had time this weekend to fix the bot and I added the feature that you requested.

You can now add additional parameters to to the calls

![image](https://user-images.githubusercontent.com/643179/82119651-8dde8500-9780-11ea-826b-99f51266a176.png)
