### ISSUE TITLE
Bot says running but doesn't come online or respond

### ISSUE THREAD

**Issue by UnbendableStraw** [rolfwessels/Command.Bot#20]
This only became an issue within the past 2 days, but I've noticed the bot no longer shows as online, doesn't respond to commands, and doesn't generate any logs (I dont think logs have worked since the dotnet update on the bot a few releases ago)

If I try to run it in a command prompt, it doesn't seem to give any insight (screenshot attached)

I tried regenerating a new token but it didn't change any behavior. I also tried another system and it runs the same way. Tried dms with the bot.

Any ideas? 

Thanks!
<img width="455" alt="Screen Shot 2020-06-24 at 11 30 53 AM" src="https://user-images.githubusercontent.com/22043907/85613819-1f0e0a80-b60f-11ea-847f-d9e5a7b3f30c.png">

**Comment by rolfwessels** [comment]
Try running `Command.Bot.Service.exe service run -v`

**Comment by rolfwessels** [comment]
I just tried it and everything seems to be working as expected on my side.

![image](https://user-images.githubusercontent.com/643179/85707099-27377a00-b6e3-11ea-92f1-22a2f83f483a.png)

**Comment by UnbendableStraw** [comment]
Shoot, I'm not sure what I'm doing wrong, it suddenly stopped working so I don't know what to make of it.
<img width="470" alt="Screen Shot 2020-06-25 at 7 13 11 AM" src="https://user-images.githubusercontent.com/22043907/85737132-f68c1c00-b6b3-11ea-99e8-605c58e434b9.png">


Here's the output with -v, same results if I try on another machine

Unfortunately no logs

Thanks~

**Comment by rolfwessels** [comment]
Strange, is there no stack trace with that error ? I cant seem to replicate the issue.

**Comment by rolfwessels** [comment]
The output looks very similar to a previous bug you posted. Are you sure that the token is correct ?  

![image](https://user-images.githubusercontent.com/643179/85848086-d7bb8180-b7a8-11ea-8cea-e1799f8b11c3.png)

**Comment by UnbendableStraw** [comment]
Ok, I think I figured it out. For some reason my api key stops working after a few days and I have to regenerate. I would replace the value in appsettings, but that alone doesn't work, once I also ran the $Env:Bot__BotKey and set the key that way, the bot worked again both in powershell and as a service. 

I'm guessing I shouldn't need to run that BotKey command and it's supposed to use the appsettings? Or was it because in the previous issue once I ran that command the first time I need to re-run it every time I change my api key?

As to why I need a new key every once in a while...no idea why that is, maybe slack isn't happy with how many reconnects the bot makes while running my scripts, they do take some time to execute

Thanks!

**Comment by rolfwessels** [comment]
Not sure why your keys reset. This has only happened to me when I accidentally uploaded my slack-key to github on a public repo.

The $Env:Bot_BotKey should override what ever is in the APP settings. Setting it in the $Env:Bot__BotKey on the command line wil only do it for that command line session. You can also add it to your global environment settings, which is personally my preferred method.

Could you elaborate on the bot re-connects ? I have not seen that happen. If you have some logs send them over then I can have a look and see if I can fix the reconnect issues.

**Comment by rolfwessels** [comment]
Closing this issue for now.

**Comment by UnbendableStraw** [comment]
Sorry for taking so long to get back to you on this...

Anyways, I asked the slack support team for help with the api keys needing reset all the time after the bot has ran for a day or so. This is what they said after they looked at the bot integration logs:

```
I've checked the logs, and found a few issue so I want to address those just in case that may be the cause of the disconnects.

In the logs, I found that you're using the rtm.start API method. 
Unfortunately, we've determined that the rtm.start API method is less efficient than rtm.connect so we've asked all developers to migrate over to using our rtm.connect API method instead (https://api.slack.com/methods/rtm.connect). We also announced this in our Platform change log here:


https://api.slack.com/changelog/2017-04-start-using-rtm-connect-and-stop-using-rtm-start

Hopefully, you're able to make that change as that should help to eliminate these errors and additionally improve performance.

While I'm mentioning that, it should be noted that we do also expect that your client detects whether or not the RTM connection is still connected by using our "Ping and Pong" method described on the following page:


https://api.slack.com/rtm#ping_and_pong

Given this, if your RTM connection does become disconnected, your client should be calling the rtm.connect (https://api.slack.com/methods/rtm.connect) endpoint again to reconnect.

Additionally, I found some rate limiting errors (https://api.slack.com/docs/rate-limits) in the logs for the rtm.start API method, but I'm hoping that when you switch over to the rtm.connect API method, they may go away.

I hope this information is helpful to you. Thanks for checking in on this.
```

**Comment by rolfwessels** [comment]
I will have to go and investigate this. I use an open source library to do the connection to slack. 

Still I am not sure they answered why the token gets blocked. Also the https://api.slack.com/docs/rate-limits talk about limits but does not talk about tokens getting blocked if limits are overrun. Either way I will try to make some time and see if I can update the slack connection. 

Thanks for the information.

**Comment by rolfwessels** [comment]
I think I found the problem. Should be fixed in https://github.com/rolfwessels/Command.Bot/releases/tag/v1.1.57
