### ISSUE TITLE
[Enhancement] enclose output to codeblock

### ISSUE THREAD

**Issue by PtrckM** [rolfwessels/Command.Bot#21]
- current output

![image](https://user-images.githubusercontent.com/54516858/86206321-b1c62080-bb9e-11ea-8fc7-6519bda2416e.png)

- propose output
![image](https://user-images.githubusercontent.com/54516858/86206401-e0dc9200-bb9e-11ea-8cc8-cb60bb4f1b05.png)

**Comment by rolfwessels** [comment]
I like that idea. I will have to see if it is possible.

**Comment by PtrckM** [comment]
- another one
![image](https://user-images.githubusercontent.com/54516858/86219152-5f8ffa00-bbb4-11ea-82c0-812c71887297.png)

- can we change it to be more informative like
bat - to see help
hello - to send hello command to you
joke1 - sends random joke about science etc.

again thanks in advance.

**Comment by rolfwessels** [comment]
Hi @PtrckM, 1 year later and I finally got around to actually implementing your request

See version
https://github.com/rolfwessels/Command.Bot/releases/tag/v1.1.57
