### ISSUE TITLE
Bot fails to reconnect / continue working sometimes after successfully executing script

### ISSUE THREAD

**Issue by UnbendableStraw** [rolfwessels/Command.Bot#30]
Lately, I've been able to execute a script from slack and it runs fine, then I will go to run another command a few minutes later and the bot doesn't respond. 

Here is the output of the debug log between the time of the last command being successfully ran, to attempting to run another one (it will keep repeating the slack disconnected message in the logs and not respond in slack until I restart the bot.

```2022-01-28 10:39:02.091 -08:00 [INF] Start executing 800
2022-01-28 10:39:04.071 -08:00 [INF] say:Copying 8.0.0.4 . Please Wait...
2022-01-28 10:39:08.067 -08:00 [INF] say:Generating MD5... 
2022-01-28 10:39:32.304 -08:00 [DBG] [WEBSOCKET CLIENT] Last message received more than 30000.00 ms ago. Hard restart..
2022-01-28 10:39:32.304 -08:00 [INF] Disconnected. Slack will try to reconnect on its own.
2022-01-28 10:39:32.304 -08:00 [DBG] [WEBSOCKET CLIENT] Reconnecting...
2022-01-28 10:39:34.066 -08:00 [INF] say:Generated MD5 Checksum
2022-01-28 10:39:34.291 -08:00 [INF] Done executing 800t in 00:00:32.2000361
2022-01-28 10:39:37.361 -08:00 [ERR] [WEBSOCKET CLIENT] Error while listening to websocket stream, error: 'The remote party closed the WebSocket connection without completing the close handshake.'
2022-01-28 10:39:37.361 -08:00 [INF] Disconnected. Slack will try to reconnect on its own.
2022-01-28 10:39:37.361 -08:00 [DBG] [WEBSOCKET CLIENT] Reconnecting...
2022-01-28 10:39:42.674 -08:00 [ERR] [WEBSOCKET CLIENT] Error while listening to websocket stream, error: 'The remote party closed the WebSocket connection without completing the close handshake.'
2022-01-28 10:39:42.674 -08:00 [INF] Disconnected. Slack will try to reconnect on its own```

**Comment by UnbendableStraw** [comment]
Anyone else having this issue? Still occuring very frequently for me

**Comment by rolfwessels** [comment]
I have not seen this issue before. I see there are some updates to the slack package that I use. I will be updating it over the next few days and let you know if there is a new release.

**Comment by rolfwessels** [comment]
Looks like the library I was using is no longer supported by the developer. His latest version is completely broken. I've switched over to slack.net. Will be testing over the next few days and let you know how it goes. (If you want to try this experimental release. You can download it from https://github.com/rolfwessels/Command.Bot/actions/runs/2550260380)

**Comment by UnbendableStraw** [comment]
Awesome, thank you! I've got it loaded up, will report back in a few days

**Comment by rolfwessels** [comment]
I run a test over the weekend and I think it's working as expected. I will keep the issue open till you have confirmed

**Comment by UnbendableStraw** [comment]
It all appears to be running fine still! No logs mentioning disconnects either~

I noticed the bot no longer gives the Typing status while it's working, and the links it sends in slack messages are no longer clicky clicky (they are now plaintext) but I'll live with this any day over the disconnects.

Tysm

**Comment by rolfwessels** [comment]
Yup, from my own testing the connection is way more stable than the other library I was using.

I noticed the typing status, I have a quick look but could not get it working. I did not notice the links. Just to confirm you echo out "HTTP://....." and they use to be clickable but not anymore?  (If not, send me a sample and I will update that)

**Comment by UnbendableStraw** [comment]
Apologies for the delay!

Still zero connection issues! 

The typing status is neat but far from a blocking issue. 

Regarding the links no longer being hyper, they are printed from my script using Write-Host if it makes any difference. Previous versions let me click the quoted links directly. Now they appear as plain text like any other text the bot prints

Sample of the line that prints the link from one of the scripts; `Write-Host "Generating MD5... You can download your package here: $fetchlink"
`

Hope this screenshot helps, this is how the messages containing links behaved before
![image](https://user-images.githubusercontent.com/22043907/177333326-491aa4b7-64c3-4cd5-a0f7-4174c6961eb2.png)

**Comment by rolfwessels** [comment]
Okay here is a new release. 🤞 it should work. 

I see the SDK I'm using will only display typing indicator if the request takes longer than 4 seconds but it's working

https://github.com/rolfwessels/Command.Bot/releases/tag/v1.2.60

**Comment by UnbendableStraw** [comment]
Typing status and linking are now working! Still no connection issues either. You rock, thank you!

**Comment by rolfwessels** [comment]
:-) thank for the compliment. I would love to take it but it mostly belongs to https://github.com/soxtoby/SlackNet. Maybe leave them a star on their repository 👍 to say thanks.
