### ISSUE TITLE
not work on Windows 10?

### ISSUE THREAD

**Issue by xukeek** [rolfwessels/Command.Bot#4]
Hello, when i call service run
Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies
Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies

**Comment by rolfwessels** [comment]
Ok, I will have a look tonight looks like I missed references.

**Comment by rolfwessels** [comment]
Hi, 

Looks like it was just an invalid binding redirect in the config sample file.

I have created a new version
https://github.com/rolfwessels/Command.Bot/releases/tag/v.0.0.4

I'm going to close the issue for now. If there are any more issues then I can just open it again.
