### ISSUE TITLE
Can't use the bot...issuing any commands in dm returns "This is not the bot you are looking for ... *wave bot like arms*"

### ISSUE THREAD

**Issue by UnbendableStraw** [rolfwessels/Command.Bot#7]
I
-created a bot on our slack workspace
-gave the bot a username
-copied the api token
-renamed the config.example to .config
-added our api token and my username "Firstname Lastname" (is it the space in the name?)
-extracted the release version of the bot into my Documents folder/CommandBot
-ran the bot using "Command.Bot.exe service run"

The command prompt I used to run the bot then says "Executing service....Press any key to stop"

Then if I go dm anything to the bot (help, batExample.bat) the bot will always return with the message "This is not the bot you are looking for ... *wave bot like arms*"

**Comment by UnbendableStraw** [comment]
Here's my config, minus the api key


[botconfig.txt](https://github.com/rolfwessels/Command.Bot/files/2968384/botconfig.txt)

**Comment by rolfwessels** [comment]
What does it say when you type 'help'?

**Comment by UnbendableStraw** [comment]
Quoting myself

"Then if I go dm anything to the bot (help, batExample.bat) the bot will always return with the message "This is not the bot you are looking for ... wave bot like arms""

I went ahead and changed my name to have no spaces on slack, just in case, that didn't seem to change anything :(

**Comment by UnbendableStraw** [comment]
Here's a the debug log:

[command.bot.console.log](https://github.com/rolfwessels/Command.Bot/files/2971958/command.bot.console.log)

**Comment by UnbendableStraw** [comment]
Lmao, the config value for AllowedUser has to match your DISPLAY NAME, not your actual NAME

I would suggest changing that to use the actual names of users, since nicknames can be changed all the time

Otherwise please update the documentation to specify matching the DISPLAY NAME

Works great otherwise, thank you!!
